#!/usr/bin/env bash
# This script displays numbers 1 to 20 with specific superstitious messages using a case statement.
COUNT=1
while [ $COUNT -le 20 ]; do
echo "$COUNT"
case $COUNT in
4) echo "bad luck from China" ;;
9) echo "bad luck from Japan" ;;
17) echo "bad luck from Italy" ;;
esac
COUNT=$((COUNT + 1))
done
